"""
JSON Validator

Responsibilities:
- Parse Gemini responses
- Remove Markdown wrappers
- Validate JSON format
- Normalize AI output
- Enforce response schema consistency
"""

import json
from copy import deepcopy


class JSONValidator:
    """
    Validates and normalizes AI JSON responses.
    """

    # Default response schema
    DEFAULT_RESPONSE = {
        "clinical_summary": "",
        "risk_level": "Low",
        "urgency": "Routine",
        "confidence_score": 0,
        "key_findings": [],
        "abnormal_findings": [],
        "possible_conditions": [],
        "differential_diagnoses": [],
        "red_flags": [],
        "recommended_tests": [],
        "doctor_recommendations": [],
        "patient_explanation": "",
        "medical_disclaimer": (
            "This analysis is generated by CareLens AI to assist "
            "healthcare professionals. It is not a medical diagnosis "
            "and should always be interpreted by a qualified clinician."
        ),
    }

    VALID_RISK_LEVELS = {
        "Low",
        "Moderate",
        "High",
        "Critical",
    }

    VALID_URGENCY = {
        "Routine",
        "Soon",
        "Urgent",
        "Emergency",
    }

    @classmethod
    def parse(cls, response_text: str) -> dict:
        """
        Parse, validate and normalize Gemini response.
        """

        cleaned = response_text.strip()

        if cleaned.startswith("```json"):
            cleaned = cleaned.replace("```json", "", 1)

        elif cleaned.startswith("```"):
            cleaned = cleaned.replace("```", "", 1)

        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]

        cleaned = cleaned.strip()

        try:
            data = json.loads(cleaned)

        except json.JSONDecodeError as e:
            raise ValueError(
                "Gemini returned invalid JSON."
            ) from e

        return cls.normalize(data)

    @classmethod
    def normalize(cls, data: dict) -> dict:
        """
        Normalize Gemini output into the expected schema.
        """

        normalized = deepcopy(cls.DEFAULT_RESPONSE)

        normalized.update(data)

        # Normalize arrays
        array_fields = [
            "key_findings",
            "abnormal_findings",
            "possible_conditions",
            "differential_diagnoses",
            "red_flags",
            "recommended_tests",
            "doctor_recommendations",
        ]

        for field in array_fields:

            value = normalized.get(field)

            if not isinstance(value, list):
                normalized[field] = []
                continue

            normalized[field] = [
                item
                for item in value
                if item not in (
                    "",
                    None,
                    "N/A",
                    "n/a",
                )
            ]

        # Normalize string fields
        string_fields = [
            "clinical_summary",
            "patient_explanation",
            "medical_disclaimer",
        ]

        for field in string_fields:

            value = normalized.get(field)

            if value is None:
                normalized[field] = ""

        # Risk level
        if normalized["risk_level"] not in cls.VALID_RISK_LEVELS:
            normalized["risk_level"] = "Low"

        # Urgency
        if normalized["urgency"] not in cls.VALID_URGENCY:
            normalized["urgency"] = "Routine"

        # Confidence Score
        try:
            confidence = int(normalized["confidence_score"])

        except Exception:
            confidence = 0

        confidence = max(0, min(confidence, 100))

        normalized["confidence_score"] = confidence

        return normalized