from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field


class AbnormalFinding(BaseModel):
    parameter: str = ""
    value: str = ""
    reference_range: str = ""
    status: str = ""
    clinical_significance: str = ""


class AIAnalysis(BaseModel):
    clinical_summary: str = ""

    risk_level: Literal[
        "Low",
        "Moderate",
        "High",
        "Critical",
    ] = "Low"

    urgency: Literal[
        "Routine",
        "Soon",
        "Urgent",
        "Emergency",
    ] = "Routine"

    confidence_score: int = Field(
        default=0,
        ge=0,
        le=100,
    )

    key_findings: list[str] = []

    abnormal_findings: list[AbnormalFinding] = []

    possible_conditions: list[str] = []

    differential_diagnoses: list[str] = []

    red_flags: list[str] = []

    recommended_tests: list[str] = []

    doctor_recommendations: list[str] = []

    patient_explanation: str = ""

    medical_disclaimer: str = (
        "This analysis is generated by CareLens AI to assist "
        "healthcare professionals. It is not a medical diagnosis "
        "and should always be interpreted by a qualified clinician."
    )


class AnalysisResponse(BaseModel):
    id: UUID
    report_id: UUID
    analysis: AIAnalysis
    created_at: datetime


class AnalysisCreateResponse(BaseModel):
    message: str
    analysis: AnalysisResponse